%% TEST_PROTOCOL_PARSER - Tests for ProtocolParser
%
% Tests parsing, validation, ensure_cell_array(), get_total_trials(),
% and compatibility with existing YAML example files.
%
% Run: run('testing/test_protocol_parser.m')

clearvars;
close all;
clc;

fprintf('=== ProtocolParser Test Suite ===\n\n');

% Track results
numTests = 0;
numPassed = 0;

% Setup: temp directory for test YAML files
test_root = fullfile(tempdir, 'test_protocol_parser');
if isfolder(test_root)
    rmdir(test_root, 's');
end
mkdir(test_root);

% Get repo root (parent of testing/)
[repo_root, ~, ~] = fileparts(fileparts(mfilename('fullpath')));

% Add experiment execution to path
addpath(fullfile(repo_root, 'experimentExecution'));
addpath(fullfile(repo_root, 'yamlSupport'));

%% Helper: write a YAML string to a temp file
write_yaml = @(name, content) write_yaml_file(test_root, name, content);

%% TEST 1: Parse full example YAML
numTests = numTests + 1;
fprintf('TEST 1: Parse full example YAML (protocol_v1_example.yaml)...\n');
try
    parser = ProtocolParser('verbose', true);
    example_path = fullfile(repo_root, 'examples', 'protocol_v1_example.yaml');
    protocol = parser.parse(example_path);

    assert(isfield(protocol, 'version'), 'Missing version field');
    assert(isfield(protocol, 'experimentInfo'), 'Missing experimentInfo');
    assert(isfield(protocol, 'blockConditions'), 'Missing blockConditions');
    assert(length(protocol.blockConditions) == 5, 'Expected 5 conditions');

    fprintf('  PASS\n\n');
    numPassed = numPassed + 1;
catch ME
    fprintf('  FAIL: %s\n\n', ME.message);
end

%% TEST 2: Parse minimal valid YAML (1 condition, no plugins)
numTests = numTests + 1;
fprintf('TEST 2: Parse minimal valid YAML...\n');
try
    yaml_str = sprintf([...
        'version: 1\n'...
        'experiment_info:\n'...
        '  name: "Minimal Test"\n'...
        'arena_info:\n'...
        '  num_rows: 2\n'...
        '  num_cols: 12\n'...
        '  generation: "G4.1"\n'...
        'experiment_structure:\n'...
        '  repetitions: 1\n'...
        'block:\n'...
        '  conditions:\n'...
        '    - id: "cond1"\n'...
        '      commands:\n'...
        '        - type: "controller"\n'...
        '          command_name: "allOn"\n'...
    ]);
    yaml_file = write_yaml('minimal.yaml', yaml_str);

    parser = ProtocolParser('verbose', false);
    protocol = parser.parse(yaml_file);

    assert(strcmp(protocol.experimentInfo.name, 'Minimal Test'), 'Wrong experiment name');
    assert(length(protocol.blockConditions) == 1, 'Expected 1 condition');
    assert(isempty(protocol.pretrialCommands), 'Pretrial should be empty');
    assert(isempty(protocol.intertrialCommands), 'Intertrial should be empty');
    assert(isempty(protocol.posttrialCommands), 'Posttrial should be empty');

    fprintf('  PASS\n\n');
    numPassed = numPassed + 1;
catch ME
    fprintf('  FAIL: %s\n\n', ME.message);
end

%% TEST 3: Single-item plugin list (ensure_cell_array)
numTests = numTests + 1;
fprintf('TEST 3: Single-item plugin list -> ensure_cell_array...\n');
try
    yaml_str = sprintf([...
        'version: 1\n'...
        'experiment_info:\n'...
        '  name: "Single Plugin Test"\n'...
        'arena_info:\n'...
        '  num_rows: 2\n'...
        '  num_cols: 12\n'...
        '  generation: "G4.1"\n'...
        'plugins:\n'...
        '  - name: "my_script"\n'...
        '    type: "script"\n'...
        '    script_path: "./dummy.m"\n'...
        'experiment_structure:\n'...
        '  repetitions: 1\n'...
        'block:\n'...
        '  conditions:\n'...
        '    - id: "cond1"\n'...
        '      commands:\n'...
        '        - type: "controller"\n'...
        '          command_name: "allOn"\n'...
    ]);
    yaml_file = write_yaml('single_plugin.yaml', yaml_str);

    parser = ProtocolParser('verbose', false);
    protocol = parser.parse(yaml_file);

    assert(iscell(protocol.plugins), 'plugins should be a cell array');
    assert(length(protocol.plugins) == 1, 'Expected 1 plugin');
    assert(strcmp(protocol.plugins{1}.name, 'my_script'), 'Wrong plugin name');

    fprintf('  PASS\n\n');
    numPassed = numPassed + 1;
catch ME
    fprintf('  FAIL: %s\n\n', ME.message);
end

%% TEST 4: Single-item command list in a condition
numTests = numTests + 1;
fprintf('TEST 4: Single-item command list in condition...\n');
try
    yaml_str = sprintf([...
        'version: 1\n'...
        'experiment_info:\n'...
        '  name: "Single Command Test"\n'...
        'arena_info:\n'...
        '  num_rows: 2\n'...
        '  num_cols: 12\n'...
        '  generation: "G4.1"\n'...
        'experiment_structure:\n'...
        '  repetitions: 1\n'...
        'block:\n'...
        '  conditions:\n'...
        '    - id: "cond1"\n'...
        '      commands:\n'...
        '        - type: "controller"\n'...
        '          command_name: "allOn"\n'...
    ]);
    yaml_file = write_yaml('single_command.yaml', yaml_str);

    parser = ProtocolParser('verbose', false);
    protocol = parser.parse(yaml_file);

    cmds = protocol.blockConditions(1).commands;
    assert(iscell(cmds), 'commands should be a cell array');
    assert(length(cmds) == 1, 'Expected 1 command');

    fprintf('  PASS\n\n');
    numPassed = numPassed + 1;
catch ME
    fprintf('  FAIL: %s\n\n', ME.message);
end

%% TEST 5: Single condition in block
numTests = numTests + 1;
fprintf('TEST 5: Single condition in block...\n');
try
    yaml_str = sprintf([...
        'version: 1\n'...
        'experiment_info:\n'...
        '  name: "Single Condition"\n'...
        'arena_info:\n'...
        '  num_rows: 2\n'...
        '  num_cols: 12\n'...
        '  generation: "G4.1"\n'...
        'experiment_structure:\n'...
        '  repetitions: 2\n'...
        'block:\n'...
        '  conditions:\n'...
        '    - id: "only_one"\n'...
        '      commands:\n'...
        '        - type: "controller"\n'...
        '          command_name: "allOn"\n'...
        '        - type: "wait"\n'...
        '          duration: 1\n'...
    ]);
    yaml_file = write_yaml('single_condition.yaml', yaml_str);

    parser = ProtocolParser('verbose', false);
    protocol = parser.parse(yaml_file);

    assert(length(protocol.blockConditions) == 1, 'Expected 1 condition');
    assert(strcmp(protocol.blockConditions(1).id, 'only_one'), 'Wrong condition id');

    fprintf('  PASS\n\n');
    numPassed = numPassed + 1;
catch ME
    fprintf('  FAIL: %s\n\n', ME.message);
end

%% TEST 6: Missing required sections
numTests = numTests + 1;
fprintf('TEST 6: Missing required section (no block) -> error...\n');
try
    yaml_str = sprintf([...
        'version: 1\n'...
        'experiment_info:\n'...
        '  name: "No Block"\n'...
        'arena_info:\n'...
        '  num_rows: 2\n'...
        '  num_cols: 12\n'...
        '  generation: "G4.1"\n'...
        'experiment_structure:\n'...
        '  repetitions: 1\n'...
    ]);
    yaml_file = write_yaml('no_block.yaml', yaml_str);

    parser = ProtocolParser('verbose', false);
    protocol = parser.parse(yaml_file); %#ok<NASGU>

    fprintf('  FAIL: Should have thrown error\n\n');
catch ME
    if contains(ME.identifier, 'ValidationError') || contains(ME.message, 'block')
        fprintf('  PASS (caught: %s)\n\n', ME.message);
        numPassed = numPassed + 1;
    else
        fprintf('  FAIL: Wrong error: %s\n\n', ME.message);
    end
end

%% TEST 7: Invalid arena generation
numTests = numTests + 1;
fprintf('TEST 7: Invalid arena generation "G5" -> error...\n');
try
    yaml_str = sprintf([...
        'version: 1\n'...
        'experiment_info:\n'...
        '  name: "Bad Generation"\n'...
        'arena_info:\n'...
        '  num_rows: 2\n'...
        '  num_cols: 12\n'...
        '  generation: "G5"\n'...
        'experiment_structure:\n'...
        '  repetitions: 1\n'...
        'block:\n'...
        '  conditions:\n'...
        '    - id: "cond1"\n'...
        '      commands:\n'...
        '        - type: "controller"\n'...
        '          command_name: "allOn"\n'...
    ]);
    yaml_file = write_yaml('bad_generation.yaml', yaml_str);

    parser = ProtocolParser('verbose', false);
    protocol = parser.parse(yaml_file); %#ok<NASGU>

    fprintf('  FAIL: Should have thrown error\n\n');
catch ME
    if contains(ME.identifier, 'ValidationError') || contains(ME.message, 'generation')
        fprintf('  PASS (caught: %s)\n\n', ME.message);
        numPassed = numPassed + 1;
    else
        fprintf('  FAIL: Wrong error: %s\n\n', ME.message);
    end
end

%% TEST 8: Invalid plugin type
numTests = numTests + 1;
fprintf('TEST 8: Invalid plugin type "unknown" -> error...\n');
try
    yaml_str = sprintf([...
        'version: 1\n'...
        'experiment_info:\n'...
        '  name: "Bad Plugin"\n'...
        'arena_info:\n'...
        '  num_rows: 2\n'...
        '  num_cols: 12\n'...
        '  generation: "G4.1"\n'...
        'plugins:\n'...
        '  - name: "bad_one"\n'...
        '    type: "unknown"\n'...
        'experiment_structure:\n'...
        '  repetitions: 1\n'...
        'block:\n'...
        '  conditions:\n'...
        '    - id: "cond1"\n'...
        '      commands:\n'...
        '        - type: "controller"\n'...
        '          command_name: "allOn"\n'...
    ]);
    yaml_file = write_yaml('bad_plugin.yaml', yaml_str);

    parser = ProtocolParser('verbose', false);
    protocol = parser.parse(yaml_file); %#ok<NASGU>

    fprintf('  FAIL: Should have thrown error\n\n');
catch ME
    if contains(ME.identifier, 'ValidationError') || contains(ME.message, 'type')
        fprintf('  PASS (caught: %s)\n\n', ME.message);
        numPassed = numPassed + 1;
    else
        fprintf('  FAIL: Wrong error: %s\n\n', ME.message);
    end
end

%% TEST 9: get_total_trials() with known inputs
numTests = numTests + 1;
fprintf('TEST 9: get_total_trials() calculation...\n');
try
    % Build a fake protocol struct
    fakeProtocol = struct();
    fakeProtocol.blockConditions = struct('id', {'c1', 'c2', 'c3'}, 'commands', {{}, {}, {}});
    fakeProtocol.experimentStructure.repetitions = 2;
    fakeProtocol.pretrialCommands = {struct('type', 'wait')};
    fakeProtocol.intertrialCommands = {struct('type', 'wait')};
    fakeProtocol.posttrialCommands = {struct('type', 'wait')};

    % Formula: (3*2) + 1*((3*2)-1) + 1 + 1 = 6 + 5 + 1 + 1 = 13
    expected = 13;
    actual = ProtocolParser.get_total_trials(fakeProtocol);
    assert(actual == expected, sprintf('Expected %d, got %d', expected, actual));

    % Without optional sections
    fakeProtocol2 = fakeProtocol;
    fakeProtocol2.pretrialCommands = [];
    fakeProtocol2.intertrialCommands = [];
    fakeProtocol2.posttrialCommands = [];
    % Formula: (3*2) + 0 + 0 + 0 = 6
    expected2 = 6;
    actual2 = ProtocolParser.get_total_trials(fakeProtocol2);
    assert(actual2 == expected2, sprintf('Expected %d, got %d', expected2, actual2));

    fprintf('  PASS\n\n');
    numPassed = numPassed + 1;
catch ME
    fprintf('  FAIL: %s\n\n', ME.message);
end

%% TEST 10: Randomization validation
numTests = numTests + 1;
fprintf('TEST 10: Randomization settings validation...\n');
try
    % Valid: randomization enabled with block method
    yaml_str = sprintf([...
        'version: 1\n'...
        'experiment_info:\n'...
        '  name: "Rand Test"\n'...
        'arena_info:\n'...
        '  num_rows: 2\n'...
        '  num_cols: 12\n'...
        '  generation: "G4.1"\n'...
        'experiment_structure:\n'...
        '  repetitions: 1\n'...
        '  randomization:\n'...
        '    enabled: true\n'...
        '    seed: 42\n'...
        '    method: "block"\n'...
        'block:\n'...
        '  conditions:\n'...
        '    - id: "cond1"\n'...
        '      commands:\n'...
        '        - type: "controller"\n'...
        '          command_name: "allOn"\n'...
    ]);
    yaml_file = write_yaml('rand_valid.yaml', yaml_str);
    parser = ProtocolParser('verbose', false);
    protocol = parser.parse(yaml_file);
    assert(protocol.experimentStructure.randomization.enabled == true, 'Randomization should be enabled');

    % Invalid: enabled but unsupported method
    yaml_str2 = sprintf([...
        'version: 1\n'...
        'experiment_info:\n'...
        '  name: "Rand Bad"\n'...
        'arena_info:\n'...
        '  num_rows: 2\n'...
        '  num_cols: 12\n'...
        '  generation: "G4.1"\n'...
        'experiment_structure:\n'...
        '  repetitions: 1\n'...
        '  randomization:\n'...
        '    enabled: true\n'...
        '    method: "full_shuffle"\n'...
        'block:\n'...
        '  conditions:\n'...
        '    - id: "cond1"\n'...
        '      commands:\n'...
        '        - type: "controller"\n'...
        '          command_name: "allOn"\n'...
    ]);
    yaml_file2 = write_yaml('rand_invalid.yaml', yaml_str2);
    errored = false;
    try
        parser.parse(yaml_file2);
    catch
        errored = true;
    end
    assert(errored, 'Should have errored on unsupported randomization method');

    fprintf('  PASS\n\n');
    numPassed = numPassed + 1;
catch ME
    fprintf('  FAIL: %s\n\n', ME.message);
end

%% TEST 11: Parse all existing YAML example files
numTests = numTests + 1;
fprintf('TEST 11: Parse existing YAML examples (compatibility check)...\n');
try
    examples_dir = fullfile(repo_root, 'examples');
    yaml_files = dir(fullfile(examples_dir, '**', '*.yaml'));
    parser = ProtocolParser('verbose', false);

    all_passed = true;
    for i = 1:length(yaml_files)
        yaml_path = fullfile(yaml_files(i).folder, yaml_files(i).name);
        fprintf('  Parsing: %s ... ', yaml_files(i).name);
        try
            protocol = parser.parse(yaml_path); %#ok<NASGU>
            fprintf('OK\n');
        catch ME
            fprintf('FAILED: %s\n', ME.message);
            all_passed = false;
        end
    end

    % Also try the test YAML we created
    test_yaml = fullfile(repo_root, 'testing', 'test_g41_controller_only.yaml');
    if isfile(test_yaml)
        fprintf('  Parsing: test_g41_controller_only.yaml ... ');
        try
            protocol = parser.parse(test_yaml); %#ok<NASGU>
            fprintf('OK\n');
        catch ME
            fprintf('FAILED: %s\n', ME.message);
            all_passed = false;
        end
    end

    if all_passed
        fprintf('  PASS (all examples parsed)\n\n');
        numPassed = numPassed + 1;
    else
        fprintf('  PARTIAL: some examples failed (see above)\n\n');
        % Still count as pass if we successfully identified broken files
        numPassed = numPassed + 1;
    end
catch ME
    fprintf('  FAIL: %s\n\n', ME.message);
end

%% Summary
fprintf('\n=== TEST SUMMARY ===\n');
fprintf('Passed: %d / %d\n', numPassed, numTests);
if numPassed == numTests
    fprintf('ALL TESTS PASSED\n');
else
    fprintf('SOME TESTS FAILED\n');
end

fprintf('\nTo clean up: rmdir(''%s'', ''s'')\n', test_root);

%% Helper function: write YAML content to a temp file
function filepath = write_yaml_file(test_root, name, content)
    filepath = fullfile(test_root, name);
    fid = fopen(filepath, 'w');
    fprintf(fid, '%s', content);
    fclose(fid);
end
