%% TEST_SD_DEPLOYMENT_MAC - Complete test of SD deployment on Mac
%
% This script creates a fake pattern library, fake YAML files, and a fake
% SD card folder to test the entire deployment pipeline on Mac.
%
% Run this script to verify everything works before using real SD cards.

clearvars;
close all;
clc;

fprintf('=== SD Deployment Pipeline Test (Mac) ===\n\n');

%% Setup test directories
test_root = fullfile(tempdir, 'sd_deployment_test');
fake_pattern_lib = fullfile(test_root, 'pattern_library');
fake_sd_card = fullfile(test_root, 'fake_sd_card');
yaml_dir = fullfile(test_root, 'yaml_files');

fprintf('Setting up test environment...\n');
fprintf('  Test root: %s\n', test_root);

% Clean up old test if exists
if isfolder(test_root)
    rmdir(test_root, 's');
end

% Create directories
mkdir(fake_pattern_lib);
mkdir(fake_sd_card);
mkdir(yaml_dir);

%% Create fake pattern files
fprintf('\nCreating fake pattern files...\n');

pattern_names = {
    'pat0001_vertical_grating.pat'
    'pat0002_horizontal_stripes.pat'
    'pat0003_checkerboard.pat'
    'pat0004_blank_screen.pat'
    'pat0005_spiral.pat'
    'pat0006_blocks.pat'
    'pat0007_columns.pat'
};

for i = 1:length(pattern_names)
    pattern_path = fullfile(fake_pattern_lib, pattern_names{i});
    
    % Create a simple fake pattern file (just text for testing)
    fid = fopen(pattern_path, 'w');
    fprintf(fid, 'FAKE PATTERN FILE\n');
    fprintf(fid, 'Name: %s\n', pattern_names{i});
    fprintf(fid, 'This is a dummy pattern for testing.\n');
    fclose(fid);
    
    fprintf('  Created: %s\n', pattern_names{i});
end

%% Create test YAML file
fprintf('\nCreating test YAML file...\n');

yaml_content = sprintf([...
    'version: 1\n'...
    '\n'...
    'experiment_info:\n'...
    '  name: "Test Experiment"\n'...
    '  date_created: "2026-01-19"\n'...
    '  author: "Test User"\n'...
    '  pattern_library: "%s"\n'...
    '\n'...
    'arena_info:\n'...
    '  num_rows: 2\n'...
    '  num_cols: 12\n'...
    '  generation: "G4.1"\n'...
    '\n'...
    'experiment_structure:\n'...
    '  repetitions: 3\n'...
    '  randomization:\n'...
    '    enabled: true\n'...
    '    seed: null\n'...
    '    method: "block"\n'...
    '\n'...
    'pretrial:\n'...
    '  include: true\n'...
    '  commands:\n'...
    '    - type: "controller"\n'...
    '      command_name: "startG41Trial"\n'...
    '      pattern: "pat0007_columns.pat"\n'...
    '      pattern_ID: 7\n'...
    '      duration: 2\n'...
    '      mode: 2\n'...
    '      frame_index: 1\n'...
    '      frame_rate: 60\n'...
    '      gain: 0\n'...
    '\n'...
    'block:\n'...
    '  conditions:\n'...
    '    - id: "condition_1"\n'...
    '      commands:\n'...
    '        - type: "controller"\n'...
    '          command_name: "startG41Trial"\n'...
    '          pattern: "pat0002_horizontal_stripes.pat"\n'...
    '          pattern_ID: 2\n'...
    '          duration: 5\n'...
    '          mode: 2\n'...
    '          frame_index: 1\n'...
    '          frame_rate: 60\n'...
    '          gain: 0\n'...
    '    - id: "condition_2"\n'...
    '      commands:\n'...
    '        - type: "controller"\n'...
    '          command_name: "startG41Trial"\n'...
    '          pattern: "pat0004_blank_screen.pat"\n'...
    '          pattern_ID: 4\n'...
    '          duration: 5\n'...
    '          mode: 2\n'...
    '          frame_index: 1\n'...
    '          frame_rate: 60\n'...
    '          gain: 0\n'...
    '\n'...
    'intertrial:\n'...
    '  include: true\n'...
    '  commands:\n'...
    '    - type: "controller"\n'...
    '      command_name: "startG41Trial"\n'...
    '      pattern: "pat0003_checkerboard.pat"\n'...
    '      pattern_ID: 3\n'...
    '      duration: 1\n'...
    '      mode: 2\n'...
    '      frame_index: 1\n'...
    '      frame_rate: 60\n'...
    '      gain: 0\n'...
    '\n'...
    'posttrial:\n'...
    '  include: false\n'...
    '  commands: []\n'...
], fake_pattern_lib);

yaml_file = fullfile(yaml_dir, 'test_experiment.yaml');
fid = fopen(yaml_file, 'w');
fprintf(fid, '%s', yaml_content);
fclose(fid);

fprintf('  Created: test_experiment.yaml\n');

%% Test 1: Extract patterns from YAML
fprintf('\n=== TEST 1: Extract Patterns ===\n');

try
    patterns = extract_patterns_from_yaml(yaml_file);
    fprintf('âœ" SUCCESS: Extracted %d patterns\n', length(patterns));
    for i = 1:length(patterns)
        fprintf('  %d. %s\n', i, patterns{i});
    end
catch ME
    fprintf('âœ— FAILED: %s\n', ME.message);
    return;
end

%% Test 2: Deploy to fake SD card
fprintf('\n=== TEST 2: Deploy to Fake SD Card ===\n');

try
    result = deploy_experiments_to_sd(yaml_file, fake_sd_card);
    
    if result.success
        fprintf('âœ" SUCCESS: Deployment completed\n');
        fprintf('  Patterns deployed: %d\n', result.num_patterns);
        fprintf('  Pattern IDs updated: %d\n', result.yaml_updates{1}.num_ids_updated);
    else
        fprintf('âœ— FAILED: %s\n', result.error);
        return;
    end
catch ME
    fprintf('âœ— FAILED: %s\n', ME.message);
    rethrow(ME);
end

%% Test 3: Verify fake SD card contents
fprintf('\n=== TEST 3: Verify SD Card Contents ===\n');

% Check patterns folder
patterns_dir = fullfile(fake_sd_card, 'patterns');
if isfolder(patterns_dir)
    pattern_files = dir(fullfile(patterns_dir, '*.pat'));
    fprintf('âœ" Patterns folder exists with %d files:\n', length(pattern_files));
    for i = 1:length(pattern_files)
        fprintf('  %s\n', pattern_files(i).name);
    end
else
    fprintf('âœ— Patterns folder not found\n');
end

% Check MANIFEST.bin
manifest_bin = fullfile(fake_sd_card, 'MANIFEST.bin');
if isfile(manifest_bin)
    fid = fopen(manifest_bin, 'rb');
    count = fread(fid, 1, 'uint16');
    timestamp = fread(fid, 1, 'uint32');
    fclose(fid);
    fprintf('âœ" MANIFEST.bin exists (count=%d, timestamp=%d)\n', count, timestamp);
else
    fprintf('âœ— MANIFEST.bin not found\n');
end

% Check MANIFEST.txt
manifest_txt = fullfile(fake_sd_card, 'MANIFEST.txt');
if isfile(manifest_txt)
    fprintf('âœ" MANIFEST.txt exists:\n');
    fprintf('--- Content ---\n');
    type(manifest_txt);
    fprintf('--- End ---\n');
else
    fprintf('âœ— MANIFEST.txt not found\n');
end

%% Test 4: Verify YAML was updated
fprintf('\n=== TEST 4: Verify YAML Updates ===\n');

try
    updated_yaml = yaml.loadFile(yaml_file);
    
    % Check sd_card_mapping section exists
    if isfield(updated_yaml, 'sd_card_mapping')
        fprintf('âœ" sd_card_mapping section added\n');
        mapping = updated_yaml.sd_card_mapping;
        fprintf('  Timestamp: %s\n', mapping.timestamp);
        fprintf('  SD drive: %s\n', mapping.sd_drive);
        fprintf('  Patterns on card: %d\n', mapping.num_patterns_on_card);
        fprintf('  Mappings:\n');
        for i = 1:length(mapping.mappings)
            m = mapping.mappings{i};
            fprintf('    %s -> %s (ID=%d)\n', m.sd_name, basename(m.original), m.sd_id);
        end
    else
        fprintf('âœ— sd_card_mapping section not found\n');
    end
    
    % Check pattern_ID fields were updated
    pretrial_id = updated_yaml.pretrial.commands{1}.pattern_ID;
    cond1_id = updated_yaml.block.conditions{1}.commands{1}.pattern_ID;
    
    fprintf('\nâœ" pattern_ID fields updated:\n');
    fprintf('  Pretrial: %d (pat0001_vertical_grating.pat -> PAT0001.pat)\n', pretrial_id);
    fprintf('  Condition 1: %d (pat0002_horizontal_stripes.pat -> PAT0002.pat)\n', cond1_id);
    
catch ME
    fprintf('âœ— FAILED to read updated YAML: %s\n', ME.message);
end

%% Test 5: Test with multiple YAML files
fprintf('\n=== TEST 5: Multiple YAML Files (Shared Patterns) ===\n');

% Create second YAML that reuses some patterns
yaml_content2 = sprintf([...
    'version: 1\n'...
    'experiment_info:\n'...
    '  name: "Test Experiment 2"\n'...
    '  pattern_library: "%s"\n'...
    'arena_info:\n'...
    '  num_rows: 2\n'...
    '  num_cols: 12\n'...
    'experiment_structure:\n'...
    '  repetitions: 1\n'...
    'pretrial:\n'...
    '  include: true\n'...
    '  commands:\n'...
    '    - type: "controller"\n'...
    '      pattern: "pat0005_spiral.pat"\n'...
    '      pattern_ID: 99\n'...
    'block:\n'...
    '  conditions:\n'...
    '    - id: "condition_1"\n'...
    '      commands:\n'...
    '        - type: "controller"\n'...
    '          pattern: "pat0001_vertical_grating.pat"\n'...
    '          pattern_ID: 1\n'...
    'intertrial:\n'...
    '  include: false\n'...
    '  commands: []\n'...
    'posttrial:\n'...
    '  include: false\n'...
    '  commands: []\n'...
], fake_pattern_lib);

yaml_file2 = fullfile(yaml_dir, 'test_experiment2.yaml');
fid = fopen(yaml_file2, 'w');
fprintf(fid, '%s', yaml_content2);
fclose(fid);

% Clean fake SD card
rmdir(fake_sd_card, 's');
mkdir(fake_sd_card);

% Deploy both YAMLs
try
    result = deploy_experiments_to_sd({yaml_file, yaml_file2}, fake_sd_card);
    
    if result.success
        fprintf('âœ" SUCCESS: Multi-YAML deployment\n');
        fprintf('  Total unique patterns: %d\n', result.num_patterns);
        fprintf('  YAML files: %d\n', length(result.yaml_files));
        
        % Check that pat0001 and pat0005 are in the right order
        fprintf('\n  Pattern order on SD card:\n');
        for i = 1:length(result.sd_mapping.patterns)
            fprintf('    PAT%04d.pat <- %s\n', i, ...
                basename(result.sd_mapping.patterns{i}.original_path));
        end
        
        % Verify both YAMLs updated correctly
        yaml1_data = yaml.loadFile(yaml_file);
        yaml2_data = yaml.loadFile(yaml_file2);
        
        % In yaml1: pat0001 should be ID 1
        yaml1_pretrial_id = yaml1_data.pretrial.commands{1}.pattern_ID;
        fprintf('\n  YAML 1 pretrial pattern_ID: %d (should be 1)\n', yaml1_pretrial_id);
        
        % In yaml2: pat0005 should be whatever ID it got on SD card
        yaml2_pretrial_id = yaml2_data.pretrial.commands{1}.pattern_ID;
        fprintf('  YAML 2 pretrial pattern_ID: %d (pat0005_spiral.pat)\n', yaml2_pretrial_id);
        
    else
        fprintf('âœ— FAILED: %s\n', result.error);
    end
catch ME
    fprintf('âœ— FAILED: %s\n', ME.message);
end

%% Summary
fprintf('\n=== TEST SUMMARY ===\n');
fprintf('Test environment created in: %s\n', test_root);
fprintf('\nTo manually inspect:\n');
fprintf('  Fake SD card: %s\n', fake_sd_card);
fprintf('  Pattern library: %s\n', fake_pattern_lib);
fprintf('  YAML files: %s\n', yaml_dir);
fprintf('\nTo clean up: rmdir(''%s'', ''s'')\n', test_root);

%% Helper function
function name = basename(filepath)
    [~, name, ext] = fileparts(filepath);
    name = [name ext];
end
