function results = compare_patterns()
% COMPARE_PATTERNS - Compare newly generated patterns against baseline
%
% This script compares patterns generated by the refactored Pattern_Generator
% against the baseline patterns created before refactoring.
%
% Run AFTER the multi-generation update to validate that G4 patterns
% are identical to the original implementation.
%
% Returns:
%   results - struct with comparison results for each pattern type

%% Setup paths
thisDir = fileparts(mfilename('fullpath'));
baselineDir = fullfile(thisDir, 'pattern_baseline');
baselineFile = fullfile(baselineDir, 'baseline_patterns.mat');

if ~exist(baselineFile, 'file')
    error(['Baseline patterns not found. Run generate_baseline_patterns.m first.\n' ...
           'File expected: %s'], baselineFile);
end

% Load baseline
fprintf('Loading baseline patterns...\n');
load(baselineFile, 'baseline');
fprintf('Baseline created: %s\n', baseline.created);

%% Check for Pattern_Generator on path
if ~exist('Pattern_Generator', 'file')
    error(['Pattern_Generator not on path. Make sure maDisplayTools is set up:\n' ...
           '  addpath(genpath(''/path/to/maDisplayTools''))']);
end

%% Setup arena (reuse baseline arena)
handles.arena_folder = fullfile(baselineDir, 'arena');
handles.arena_file = 'arena_parameters.mat';

%% Compare each pattern type
patterns = {'square_grating', 'sine_grating', 'edge', 'starfield', 'off_on'};
results = struct();
all_passed = true;

for i = 1:length(patterns)
    pname = patterns{i};
    fprintf('\n=== Comparing %s ===\n', strrep(pname, '_', ' '));

    % Get baseline
    bl = baseline.(pname);

    % Regenerate with new code
    handles.param = bl.param;

    % For starfield, reset random seed
    if strcmp(pname, 'starfield')
        rng(42);
    end

    try
        [Pats_new, true_step_new, rot180_new] = Pattern_Generator(handles);

        % Compare results
        results.(pname).generated = true;

        % Check dimensions
        size_match = isequal(size(Pats_new), size(bl.Pats));
        results.(pname).size_match = size_match;
        fprintf('  Size match: %s (baseline: [%s], new: [%s])\n', ...
            bool2str(size_match), ...
            num2str(size(bl.Pats)), num2str(size(Pats_new)));

        % Check pixel values (exact match)
        if size_match
            pixel_match = isequal(Pats_new, bl.Pats);
            results.(pname).pixel_match = pixel_match;

            if ~pixel_match
                diff_count = sum(Pats_new(:) ~= bl.Pats(:));
                max_diff = max(abs(double(Pats_new(:)) - double(bl.Pats(:))));
                results.(pname).diff_count = diff_count;
                results.(pname).max_diff = max_diff;
                fprintf('  Pixel match: FAILED (%d pixels differ, max diff: %d)\n', ...
                    diff_count, max_diff);
            else
                fprintf('  Pixel match: PASSED (exact match)\n');
            end
        else
            results.(pname).pixel_match = false;
            fprintf('  Pixel match: SKIPPED (size mismatch)\n');
        end

        % Check true_step_size
        step_match = abs(true_step_new - bl.true_step_size) < 1e-10;
        results.(pname).step_match = step_match;
        fprintf('  Step size match: %s (baseline: %.6f, new: %.6f)\n', ...
            bool2str(step_match), bl.true_step_size, true_step_new);

        % Check rot180
        rot_match = (rot180_new == bl.rot180);
        results.(pname).rot180_match = rot_match;
        fprintf('  rot180 match: %s\n', bool2str(rot_match));

        % Overall pass/fail
        passed = size_match && results.(pname).pixel_match && step_match && rot_match;
        results.(pname).passed = passed;

        if ~passed
            all_passed = false;
        end

    catch ME
        results.(pname).generated = false;
        results.(pname).error = ME.message;
        results.(pname).passed = false;
        all_passed = false;
        fprintf('  ERROR: %s\n', ME.message);
    end
end

%% Summary
fprintf('\n');
fprintf('=========================================\n');
fprintf('           VALIDATION SUMMARY            \n');
fprintf('=========================================\n');
fprintf('\n');

for i = 1:length(patterns)
    pname = patterns{i};
    if results.(pname).passed
        status = 'PASSED';
    else
        status = 'FAILED';
    end
    fprintf('  %-15s : %s\n', strrep(pname, '_', ' '), status);
end

fprintf('\n');
if all_passed
    fprintf('  OVERALL: ALL TESTS PASSED\n');
else
    fprintf('  OVERALL: SOME TESTS FAILED\n');
end
fprintf('\n');
fprintf('=========================================\n');

%% Save results
resultsFile = fullfile(baselineDir, 'comparison_results.mat');
comparison.results = results;
comparison.timestamp = datestr(now, 'yyyy-mm-dd HH:MM:SS');
comparison.all_passed = all_passed;
save(resultsFile, 'comparison');
fprintf('\nResults saved to: %s\n', resultsFile);

end

function s = bool2str(b)
    if b
        s = 'YES';
    else
        s = 'NO';
    end
end
