classdef test_protocol_parser < matlab.unittest.TestCase
    % TEST_PROTOCOL_PARSER - Unit tests for ProtocolParser
    %
    % Tests parsing, validation, ensure_cell_array(), get_total_trials(),
    % and compatibility with existing YAML example files.
    %
    % Run: run(test_protocol_parser)
    
    properties
        testRoot
        repoRoot
    end
    
    methods (TestClassSetup)
        function setupTestEnvironment(testCase)
            % Setup: temp directory for test YAML files
            testCase.testRoot = fullfile(tempdir, 'test_protocol_parser');
            if isfolder(testCase.testRoot)
                rmdir(testCase.testRoot, 's');
            end
            mkdir(testCase.testRoot);
            
            % Get repo root (assumes test file is in tests/unit/)
            testCase.repoRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
            
            % Add paths
            addpath(fullfile(testCase.repoRoot, 'experimentExecution'));
            addpath(fullfile(testCase.repoRoot, 'yamlSupport'));
        end
    end
    
    methods (TestClassTeardown)
        function cleanupTestEnvironment(testCase)
            % Clean up temp directory
            if isfolder(testCase.testRoot)
                rmdir(testCase.testRoot, 's');
            end
        end
    end
    
    methods (Test)
        function testParseFullExampleYaml(testCase)
            % Parse full example YAML (protocol_v1_example.yaml)
            parser = ProtocolParser('verbose', true);
            example_path = fullfile(testCase.repoRoot, 'examples', 'protocol_v1_example.yaml');
            protocol = parser.parse(example_path);
            
            testCase.verifyTrue(isfield(protocol, 'version'), 'Missing version field');
            testCase.verifyTrue(isfield(protocol, 'experimentInfo'), 'Missing experimentInfo');
            testCase.verifyTrue(isfield(protocol, 'blockConditions'), 'Missing blockConditions');
            testCase.verifyEqual(length(protocol.blockConditions), 5, 'Expected 5 conditions');
        end
        
        function testParseMinimalValidYaml(testCase)
            % Parse minimal valid YAML (1 condition, no plugins)
            yaml_str = sprintf([...
                'version: 1\n'...
                'experiment_info:\n'...
                '  name: "Minimal Test"\n'...
                'arena_info:\n'...
                '  num_rows: 2\n'...
                '  num_cols: 12\n'...
                '  generation: "G4.1"\n'...
                'experiment_structure:\n'...
                '  repetitions: 1\n'...
                'block:\n'...
                '  conditions:\n'...
                '    - id: "cond1"\n'...
                '      commands:\n'...
                '        - type: "controller"\n'...
                '          command_name: "allOn"\n'...
            ]);
            yaml_file = testCase.writeYamlFile('minimal.yaml', yaml_str);
            
            parser = ProtocolParser('verbose', false);
            protocol = parser.parse(yaml_file);
            
            testCase.verifyEqual(protocol.experimentInfo.name, 'Minimal Test', 'Wrong experiment name');
            testCase.verifyEqual(length(protocol.blockConditions), 1, 'Expected 1 condition');
            testCase.verifyEmpty(protocol.pretrialCommands, 'Pretrial should be empty');
            testCase.verifyEmpty(protocol.intertrialCommands, 'Intertrial should be empty');
            testCase.verifyEmpty(protocol.posttrialCommands, 'Posttrial should be empty');
        end
        
        function testSingleItemPluginListNormalization(testCase)
            % Single-item plugin list should be normalized to cell array
            yaml_str = sprintf([...
                'version: 1\n'...
                'experiment_info:\n'...
                '  name: "Single Plugin Test"\n'...
                'arena_info:\n'...
                '  num_rows: 2\n'...
                '  num_cols: 12\n'...
                '  generation: "G4.1"\n'...
                'plugins:\n'...
                '  - name: "my_script"\n'...
                '    type: "script"\n'...
                '    script_path: "./dummy.m"\n'...
                'experiment_structure:\n'...
                '  repetitions: 1\n'...
                'block:\n'...
                '  conditions:\n'...
                '    - id: "cond1"\n'...
                '      commands:\n'...
                '        - type: "controller"\n'...
                '          command_name: "allOn"\n'...
            ]);
            yaml_file = testCase.writeYamlFile('single_plugin.yaml', yaml_str);
            
            parser = ProtocolParser('verbose', false);
            protocol = parser.parse(yaml_file);
            
            testCase.verifyTrue(iscell(protocol.plugins), 'plugins should be a cell array');
            testCase.verifyEqual(length(protocol.plugins), 1, 'Expected 1 plugin');
            testCase.verifyEqual(protocol.plugins{1}.name, 'my_script', 'Wrong plugin name');
        end
        
        function testSingleItemCommandListNormalization(testCase)
            % Single-item command list in condition should be normalized to cell array
            yaml_str = sprintf([...
                'version: 1\n'...
                'experiment_info:\n'...
                '  name: "Single Command Test"\n'...
                'arena_info:\n'...
                '  num_rows: 2\n'...
                '  num_cols: 12\n'...
                '  generation: "G4.1"\n'...
                'experiment_structure:\n'...
                '  repetitions: 1\n'...
                'block:\n'...
                '  conditions:\n'...
                '    - id: "cond1"\n'...
                '      commands:\n'...
                '        - type: "controller"\n'...
                '          command_name: "allOn"\n'...
            ]);
            yaml_file = testCase.writeYamlFile('single_command.yaml', yaml_str);
            
            parser = ProtocolParser('verbose', false);
            protocol = parser.parse(yaml_file);
            
            cmds = protocol.blockConditions(1).commands;
            testCase.verifyTrue(iscell(cmds), 'commands should be a cell array');
            testCase.verifyEqual(length(cmds), 1, 'Expected 1 command');
        end
        
        function testSingleConditionNormalization(testCase)
            % Single condition in block should be handled correctly
            yaml_str = sprintf([...
                'version: 1\n'...
                'experiment_info:\n'...
                '  name: "Single Condition"\n'...
                'arena_info:\n'...
                '  num_rows: 2\n'...
                '  num_cols: 12\n'...
                '  generation: "G4.1"\n'...
                'experiment_structure:\n'...
                '  repetitions: 2\n'...
                'block:\n'...
                '  conditions:\n'...
                '    - id: "only_one"\n'...
                '      commands:\n'...
                '        - type: "controller"\n'...
                '          command_name: "allOn"\n'...
                '        - type: "wait"\n'...
                '          duration: 1\n'...
            ]);
            yaml_file = testCase.writeYamlFile('single_condition.yaml', yaml_str);
            
            parser = ProtocolParser('verbose', false);
            protocol = parser.parse(yaml_file);
            
            testCase.verifyEqual(length(protocol.blockConditions), 1, 'Expected 1 condition');
            testCase.verifyEqual(protocol.blockConditions(1).id, 'only_one', 'Wrong condition id');
        end
        
        function testMissingRequiredSection(testCase)
            % YAML missing required 'block' section should error
            yaml_str = sprintf([...
                'version: 1\n'...
                'experiment_info:\n'...
                '  name: "No Block"\n'...
                'arena_info:\n'...
                '  num_rows: 2\n'...
                '  num_cols: 12\n'...
                '  generation: "G4.1"\n'...
                'experiment_structure:\n'...
                '  repetitions: 1\n'...
            ]);
            yaml_file = testCase.writeYamlFile('no_block.yaml', yaml_str);
            
            parser = ProtocolParser('verbose', false);
            
            testCase.verifyError(@() parser.parse(yaml_file), 'ProtocolParser:ValidationError', ...
                'Should error on missing block section');
        end
        
        function testInvalidArenaGeneration(testCase)
            % Invalid arena generation "G5" should error
            yaml_str = sprintf([...
                'version: 1\n'...
                'experiment_info:\n'...
                '  name: "Bad Generation"\n'...
                'arena_info:\n'...
                '  num_rows: 2\n'...
                '  num_cols: 12\n'...
                '  generation: "G5"\n'...
                'experiment_structure:\n'...
                '  repetitions: 1\n'...
                'block:\n'...
                '  conditions:\n'...
                '    - id: "cond1"\n'...
                '      commands:\n'...
                '        - type: "controller"\n'...
                '          command_name: "allOn"\n'...
            ]);
            yaml_file = testCase.writeYamlFile('bad_generation.yaml', yaml_str);
            
            parser = ProtocolParser('verbose', false);
            
            testCase.verifyError(@() parser.parse(yaml_file), 'ProtocolParser:ValidationError', ...
                'Should error on invalid generation');
        end
        
        function testInvalidPluginType(testCase)
            % Invalid plugin type "unknown" should error
            yaml_str = sprintf([...
                'version: 1\n'...
                'experiment_info:\n'...
                '  name: "Bad Plugin"\n'...
                'arena_info:\n'...
                '  num_rows: 2\n'...
                '  num_cols: 12\n'...
                '  generation: "G4.1"\n'...
                'plugins:\n'...
                '  - name: "bad_one"\n'...
                '    type: "unknown"\n'...
                'experiment_structure:\n'...
                '  repetitions: 1\n'...
                'block:\n'...
                '  conditions:\n'...
                '    - id: "cond1"\n'...
                '      commands:\n'...
                '        - type: "controller"\n'...
                '          command_name: "allOn"\n'...
            ]);
            yaml_file = testCase.writeYamlFile('bad_plugin.yaml', yaml_str);
            
            parser = ProtocolParser('verbose', false);
            
            testCase.verifyError(@() parser.parse(yaml_file), 'ProtocolParser:ValidationError', ...
                'Should error on invalid plugin type');
        end
        
        function testGetTotalTrialsCalculation(testCase)
            % Test get_total_trials() calculation with known inputs
            
            % Build a fake protocol struct
            fakeProtocol = struct();
            fakeProtocol.blockConditions = struct('id', {'c1', 'c2', 'c3'}, 'commands', {{}, {}, {}});
            fakeProtocol.experimentStructure.repetitions = 2;
            fakeProtocol.pretrialCommands = {struct('type', 'wait')};
            fakeProtocol.intertrialCommands = {struct('type', 'wait')};
            fakeProtocol.posttrialCommands = {struct('type', 'wait')};
            
            % Formula: (3*2) + 1*((3*2)-1) + 1 + 1 = 6 + 5 + 1 + 1 = 13
            expected = 13;
            actual = ProtocolParser.get_total_trials(fakeProtocol);
            testCase.verifyEqual(actual, expected, ...
                sprintf('Expected %d trials, got %d', expected, actual));
            
            % Without optional sections
            fakeProtocol2 = fakeProtocol;
            fakeProtocol2.pretrialCommands = [];
            fakeProtocol2.intertrialCommands = [];
            fakeProtocol2.posttrialCommands = [];
            % Formula: (3*2) + 0 + 0 + 0 = 6
            expected2 = 6;
            actual2 = ProtocolParser.get_total_trials(fakeProtocol2);
            testCase.verifyEqual(actual2, expected2, ...
                sprintf('Expected %d trials, got %d', expected2, actual2));
        end
        
        function testRandomizationValidation(testCase)
            % Test randomization settings validation
            
            % Valid: randomization enabled with block method
            yaml_str = sprintf([...
                'version: 1\n'...
                'experiment_info:\n'...
                '  name: "Rand Test"\n'...
                'arena_info:\n'...
                '  num_rows: 2\n'...
                '  num_cols: 12\n'...
                '  generation: "G4.1"\n'...
                'experiment_structure:\n'...
                '  repetitions: 1\n'...
                '  randomization:\n'...
                '    enabled: true\n'...
                '    seed: 42\n'...
                '    method: "block"\n'...
                'block:\n'...
                '  conditions:\n'...
                '    - id: "cond1"\n'...
                '      commands:\n'...
                '        - type: "controller"\n'...
                '          command_name: "allOn"\n'...
            ]);
            yaml_file = testCase.writeYamlFile('rand_valid.yaml', yaml_str);
            parser = ProtocolParser('verbose', false);
            protocol = parser.parse(yaml_file);
            testCase.verifyTrue(protocol.experimentStructure.randomization.enabled, ...
                'Randomization should be enabled');
            
            % Invalid: enabled but unsupported method
            yaml_str2 = sprintf([...
                'version: 1\n'...
                'experiment_info:\n'...
                '  name: "Rand Bad"\n'...
                'arena_info:\n'...
                '  num_rows: 2\n'...
                '  num_cols: 12\n'...
                '  generation: "G4.1"\n'...
                'experiment_structure:\n'...
                '  repetitions: 1\n'...
                '  randomization:\n'...
                '    enabled: true\n'...
                '    method: "full_shuffle"\n'...
                'block:\n'...
                '  conditions:\n'...
                '    - id: "cond1"\n'...
                '      commands:\n'...
                '        - type: "controller"\n'...
                '          command_name: "allOn"\n'...
            ]);
            yaml_file2 = testCase.writeYamlFile('rand_invalid.yaml', yaml_str2);
            
            testCase.verifyError(@() parser.parse(yaml_file2), 'ProtocolParser:ValidationError', ...
                'Should error on unsupported randomization method');
        end
        
        function testParseExistingYamlExamples(testCase)
            % Parse all existing YAML example files that are experiment protocols.
            % Skips non-protocol YAML files (templates, lab tests, etc.)
            % by checking for a top-level 'version' field.
            examples_dir = fullfile(testCase.repoRoot, 'examples');
            yaml_files = dir(fullfile(examples_dir, '**', '*.yaml'));
            parser = ProtocolParser('verbose', false);

            for i = 1:length(yaml_files)
                yaml_path = fullfile(yaml_files(i).folder, yaml_files(i).name);

                % Pre-screen: only parse files with top-level 'version' key
                % (this identifies experiment protocol files vs templates,
                %  lab test configs, or other YAML formats)
                try
                    raw = yamlread(yaml_path);
                catch
                    continue;  % Skip files that can't be read as YAML
                end
                if ~isstruct(raw) || ~isfield(raw, 'version')
                    continue;  % Not an experiment protocol file
                end

                % Test that each protocol example parses without error
                try
                    protocol = parser.parse(yaml_path); %#ok<NASGU>
                catch ME
                    testCase.verifyFail(sprintf('Failed to parse %s: %s', ...
                        yaml_files(i).name, ME.message));
                end
            end

            % Also try the test YAML
            test_yaml = fullfile(testCase.repoRoot, 'testing', 'test_g41_controller_only.yaml');
            if isfile(test_yaml)
                try
                    protocol = parser.parse(test_yaml); %#ok<NASGU>
                catch ME
                    testCase.verifyFail(sprintf('Failed to parse test_g41_controller_only.yaml: %s', ...
                        ME.message));
                end
            end
        end
    end
    
    methods (Access = private)
        function filepath = writeYamlFile(testCase, name, content)
            % Helper: write YAML content to a temp file
            filepath = fullfile(testCase.testRoot, name);
            fid = fopen(filepath, 'w');
            fprintf(fid, '%s', content);
            fclose(fid);
        end
    end
end
